#!/bin/bash

#SBATCH -A mcintoshgroup_gpu
#SBATCH --reservation=mcintoshgroup_gpu1
#SBATCH -t 70:00:00
#SBATCH --mem=40G
#SBATCH -J abaltion_zero_shot
#SBATCH -p gpu
#SBATCH -c 10
#SBATCH -N 1
#SBATCH --gres=gpu:l40:1
#SBATCH --begin=now

source activate ctclip

# final model used in the manuscript
python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_Swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1.0__ctcl_1.0__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_Swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1.0__ctcl_1.0__pretrained_False_50_epoch zero_shot_params.test_bed=ct-rate

# zero shot performance on different pretrained configuration (diagonal of the ablation matrix), since these are equal weighting factor => no need
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.1__ctcl_0.1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.2__ctcl_0.2__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.4__ctcl_0.4__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.8__ctcl_0.8__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1__ctcl_1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate

# non-diagonal of the ablation matrix
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.1__ctcl_0.2__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.1__ctcl_0.4__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.1__ctcl_0.8__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.1__ctcl_1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate

# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.2__ctcl_0.1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.2__ctcl_0.4__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.2__ctcl_0.8__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.2__ctcl_1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate

# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.4__ctcl_0.1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.4__ctcl_0.2__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.4__ctcl_0.8__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.4__ctcl_1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate

# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.8__ctcl_0.1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.8__ctcl_0.2__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
# python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.8__ctcl_0.4__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_0.8__ctcl_1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate

python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1__ctcl_0.1__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1__ctcl_0.2__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1__ctcl_0.4__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate
python /cluster/home/t135419uhn/CT-CLIP/scripts/run_xray_zero_shot.py base.is_ablation_study=true zero_shot_params.baseline_type=modeltype_cxr_clip_swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1__ctcl_0.8__pretrained_True_50_epoch zero_shot_params.test_bed=ct-rate