name: "clip_custom"
temperature: 0.07

image_encoder:
  source: "huggingface" # one of { "huggingface"}
  name: 'microsoft/swin-tiny-patch4-window7-224'
  pretrained: true
  model_type: 'swin'
  cache_dir: '/mnt/c/Users/MaxYo/OneDrive/Desktop/MBP/Chris/CT-CLIP/predownloaded_models/cxr-swinTiny/' 
  # '/cluster/home/t135419uhn/CT-CLIP/predownloaded_models/cxr-swinTiny/'
  # '/mnt/c/Users/MaxYo/OneDrive/Desktop/MBP/Chris/CT-CLIP/predownloaded_models/cxr-swinTiny/' 

text_encoder:
  source: "huggingface" # one of { "huggingface"}
  name: emilyalsentzer/Bio_ClinicalBERT
  pretrained: true
  gradient_checkpointing: false
  pooling: "eos" # one of { "eos" | "bos" | "mean" }
  cache_dir: "./huggingface_downloads/"
  trust_remote_code: true
  mlm_head: true

projection_head: # optional
  name: "linear" # one of { "linear" | "mlp" }
  dropout: 0.1
  proj_dim: 512
