defaults:
  - _self_

base:
  seed: 1234

## NOTE: train script version
training_params:
  batch_size: 2
  num_workers: 5
  batch_style: instance
  epoch_based_patience: 10
  iteration_evaluate_frequency: 5
  learning_rate: 5e-5
  weight_decay: 1e-4
  epochs: 2
  min_epochs: 50

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
