defaults:
  - _self_
  - data_train:
    - mimic_cxr
    - chexpert
  - data_valid:
    - mimic_cxr
    - chexpert
  - dataloader: dataloader_128
  - tokenizer: clinical_bert
  - transform: clahe
  - model: clip_swin_clinical # clip_resnet_clinical #
  - optimizer: adamw
  - scheduler: cosine_epoch15_warmup1
  - loss: cxr_clip

base:
  seed: 1234
  amp : True
  image_size: 224
  text_max_length: 256
  loss_best: contrastive
  data_frac: 1.0
  output:
    checkpoint: ${hydra:run.dir}/checkpoints/
    tensorboard: ${hydra:run.dir}/tensorboard/
  
baseline_type: 'cxr_clip'
  
training_params:
  batch_size: 360
  num_workers: 10
  batch_style: experiment
  train_from_scratch: false
  epoch_based_patience: 25
  iteration_evaluate_frequency: 50
  text_cl_weight: 1.0
  ct_cl_weight: 1.0
  learning_rate: 5e-5
  weight_decay: 1e-4
  epochs: 52
  min_epochs: 51
  use_pretrained_xray_encoder: false

linear_probing_params:
  is_linear_probe_eval: true
  is_evaluate_our_model: false
  num_epochs: 500 # 500
  patience: 20
  batch_size: 1024
  learning_rate: 1e-3 # 1e-3
  progress_window: 5
  num_workers: 10
  ckpt_name: '' #'modeltype_Swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1.0__ctcl_1.0__pretrained_True_50_epoch'
  train_data_portion: 1.
  cpt_dest: '/cluster/projects/mcintoshgroup/CT-RATE-CHECKPOINTS/classification_evaluation'

# for testing
# external_linear_probing_params:
#   is_linear_probe_eval: true
#   is_evaluate_our_model: true
#   num_epochs: 200 # 200
#   patience: 20
#   batch_size: 1024
#   learning_rate: 1e-3 # 1e-3
#   progress_window: 5
#   num_workers: 10
#   ckpt_name: 'modeltype_Swin__batchstyle_experiment__bs_360__lr_5e-05__wd_0.0001__textcl_1.0__ctcl_1.0__pretrained_True_50_epoch'
#   train_data_portion: .2
#   cpt_dest: '/cluster/projects/mcintoshgroup/CT-RATE-CHECKPOINTS/classification_evaluation_mimic'

retrieval_params:
  filter_patient_instances: true

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
