defaults:
  - _self_

base:
  seed: 1234

## NOTE: train script version
training_params:
  batch_size: 2
  num_workers: 10
  batch_style: instance
  epoch_based_patience: 100
  iteration_evaluate_frequency: 200 # prevent iteration based evaluation
  learning_rate: 2e-5
  weight_decay: 1e-4
  epochs: 100
  min_epochs: 100

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
